name: bridge_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+43

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  google_fonts: ^8.0.2
  flutter_animate: ^4.5.2
  flutter_riverpod: ^2.5.1
  http: ^1.6.0
  speech_to_text: ^7.3.0
  font_awesome_flutter: ^10.12.0
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  image_picker: ^1.2.1
  file_picker: ^8.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#0D0D12"
  adaptive_icon_foreground: "assets/logo.png"
